package dad.models.estructura;

public enum MetodoEvolucion {

	NIVEL, PIEDRA, INTERCAMBIO, INTERCAMBIOCONOBJETO, FELICIDAD, BELLEZA, ESTADISTICAS, MOVIMIENTO, LUGAR, NIVELOBJETO,
	GENERO, COMPANIERO, POSICION, CLIMA, AFECTO, VERSIONJUEGO;

}
