package dad.Models.estructura;

public enum Metodo {

	NIVEL, PIEDRA, INTERCAMBIO, INTERCAMBIOCONOBJETO, FELICIDAD, BELLEZA, ESTADISTICAS, MOVIMIENTO, LUGAR, NIVELOBJETO,
	GENERO, COMPANIERO, POSICION, CLIMA, AFECTO, VERSIONJUEGO;

}
